const iconJson = [
    {
        "folderId": 2,
        "companyId": 1,
        "parentId": null,
        "folderNameShort": "Regeneron",
        "folderNameLong": "Regeneron Folder",
        "folderDescription": null,
        "permissionLevelId": 2,
        "permissionName": "WRITE",
        "permissionIcon": "edit.png",
        "userId": 1,
        "userEmail": "mr.toshio.kimura@gmail.com",
        "accountGroupId": null,
        "accountGroupName": null,
        "image":"http://giblets-001-site2.dtempurl.com/images/icon/parameter-database.png"
    },
    {
        "folderId": 3,
        "companyId": 1,
        "parentId": 2,
        "folderNameShort": "BDM",
        "folderNameLong": "BDM Folder",
        "folderDescription": null,
        "permissionLevelId": null,
        "permissionName": null,
        "permissionIcon": null,
        "userId": null,
        "userEmail": null,
        "accountGroupId": null,
        "accountGroupName": null,
        "image": "http://giblets-001-site2.dtempurl.com/images/icon/subfolder-database.png"
    },
    {
        "folderId": 7,
        "companyId": 1,
        "parentId": 2,
        "folderNameShort": "Medical Affairs",
        "folderNameLong": "Medical Affairs Folder",
        "folderDescription": null,
        "permissionLevelId": null,
        "permissionName": null,
        "permissionIcon": null,
        "userId": null,
        "userEmail": null,
        "accountGroupId": null,
        "accountGroupName": null,
        "image": "http://giblets-001-site2.dtempurl.com/images/icon/subfolder-database.png"
    },
    {
        "folderId": 17,
        "companyId": 1,
        "parentId": 2,
        "folderNameShort": "PK",
        "folderNameLong": "PK Folder",
        "folderDescription": null,
        "permissionLevelId": null,
        "permissionName": null,
        "permissionIcon": null,
        "userId": null,
        "userEmail": null,
        "accountGroupId": null,
        "accountGroupName": null,
        "image": "http://giblets-001-site2.dtempurl.com/images/icon/subfolder-database.png"
    },
    {
        "folderId": 384,
        "companyId": 1,
        "parentId": null,
        "folderNameShort": "Immunology",
        "folderNameLong": "Immunology",
        "folderDescription": null,
        "permissionLevelId": 4,
        "permissionName": "DENY",
        "permissionIcon": "denyicon.png",
        "userId": 1,
        "userEmail": "mr.toshio.kimura@gmail.com",
        "accountGroupId": null,
        "accountGroupName": null,
        "image": "http://giblets-001-site2.dtempurl.com/images/icon/parameter-database.png"
    },
    {
        "folderId": 385,
        "companyId": 1,
        "parentId": null,
        "folderNameShort": "Ophthamology",
        "folderNameLong": "Ophthamology",
        "folderDescription": null,
        "permissionLevelId": 1,
        "permissionName": "READ",
        "permissionIcon": "view.png",
        "userId": 1,
        "userEmail": "mr.toshio.kimura@gmail.com",
        "accountGroupId": null,
        "accountGroupName": null,
        "image": "http://giblets-001-site2.dtempurl.com/images/icon/subfolder-database.png"
    },
    {
        "folderId": 386,
        "companyId": 1,
        "parentId": null,
        "folderNameShort": "Oncology",
        "folderNameLong": "Oncology",
        "folderDescription": null,
        "permissionLevelId": 3,
        "permissionName": "FULL",
        "permissionIcon": "unlockiconblack.png",
        "userId": 1,
        "userEmail": "mr.toshio.kimura@gmail.com",
        "accountGroupId": null,
        "accountGroupName": null,
        "image": "http://giblets-001-site2.dtempurl.com/images/icon/subfolder-database.png"
    },
    {
        "folderId": 387,
        "companyId": 1,
        "parentId": null,
        "folderNameShort": "General Medicine",
        "folderNameLong": "General Medicine",
        "folderDescription": null,
        "permissionLevelId": 4,
        "permissionName": "DENY",
        "permissionIcon": "denyicon.png",
        "userId": 1,
        "userEmail": "mr.toshio.kimura@gmail.com",
        "accountGroupId": null,
        "accountGroupName": null,
        "image": "http://giblets-001-site2.dtempurl.com/images/icon/subfolder-database.png"
    },
    {
        "folderId": 388,
        "companyId": 1,
        "parentId": 384,
        "folderNameShort": "R1234",
        "folderNameLong": "R1234",
        "folderDescription": null,
        "permissionLevelId": null,
        "permissionName": null,
        "permissionIcon": null,
        "userId": null,
        "userEmail": null,
        "accountGroupId": null,
        "accountGroupName": null,
        "image": "http://giblets-001-site2.dtempurl.com/images/icon/subfolder-database.png"
    },
    {
        "folderId": 412,
        "companyId": 1,
        "parentId": 384,
        "folderNameShort": "R3456",
        "folderNameLong": "R3456",
        "folderDescription": null,
        "permissionLevelId": null,
        "permissionName": null,
        "permissionIcon": null,
        "userId": null,
        "userEmail": null,
        "accountGroupId": null,
        "accountGroupName": null,
        "image": "http://giblets-001-site2.dtempurl.com/images/icon/subfolder-database.png"
    },
    {
        "folderId": 429,
        "companyId": 1,
        "parentId": 387,
        "folderNameShort": "R272",
        "folderNameLong": "R272",
        "folderDescription": null,
        "permissionLevelId": null,
        "permissionName": null,
        "permissionIcon": null,
        "userId": null,
        "userEmail": null,
        "accountGroupId": null,
        "accountGroupName": null,
        "image": "http://giblets-001-site2.dtempurl.com/images/icon/subfolder-database.png"
    },
    {
        "folderId": 443,
        "companyId": 1,
        "parentId": 386,
        "folderNameShort": "R4891",
        "folderNameLong": "R4891",
        "folderDescription": null,
        "permissionLevelId": null,
        "permissionName": null,
        "permissionIcon": null,
        "userId": null,
        "userEmail": null,
        "accountGroupId": null,
        "accountGroupName": null,
        "image": "http://giblets-001-site2.dtempurl.com/images/icon/subfolder-database.png"
    },
    {
        "folderId": 452,
        "companyId": 1,
        "parentId": 388,
        "folderNameShort": "R1234-AD",
        "folderNameLong": "R1234-AD",
        "folderDescription": null,
        "permissionLevelId": null,
        "permissionName": null,
        "permissionIcon": null,
        "userId": null,
        "userEmail": null,
        "accountGroupId": null,
        "accountGroupName": null,
        "image": "http://giblets-001-site2.dtempurl.com/images/icon/subfolder-database.png"
    },
    {
        "folderId": 453,
        "companyId": 1,
        "parentId": 388,
        "folderNameShort": "R1234-AS",
        "folderNameLong": "R1234-AS",
        "folderDescription": null,
        "permissionLevelId": null,
        "permissionName": null,
        "permissionIcon": null,
        "userId": null,
        "userEmail": null,
        "accountGroupId": null,
        "accountGroupName": null,
        "image": "http://giblets-001-site2.dtempurl.com/images/icon/subfolder-database.png"
    },
    {
        "folderId": 454,
        "companyId": 1,
        "parentId": 388,
        "folderNameShort": "R1234-NP",
        "folderNameLong": "R1234-NP",
        "folderDescription": null,
        "permissionLevelId": null,
        "permissionName": null,
        "permissionIcon": null,
        "userId": null,
        "userEmail": null,
        "accountGroupId": null,
        "accountGroupName": null,
        "image": "http://giblets-001-site2.dtempurl.com/images/icon/subfolder-database.png"
    },
    {
        "folderId": 455,
        "companyId": 1,
        "parentId": 412,
        "folderNameShort": "R3456-AS",
        "folderNameLong": "R3456-AS",
        "folderDescription": null,
        "permissionLevelId": null,
        "permissionName": null,
        "permissionIcon": null,
        "userId": null,
        "userEmail": null,
        "accountGroupId": null,
        "accountGroupName": null,
        "image": "http://giblets-001-site2.dtempurl.com/images/icon/subfolder-database.png"
    },
    {
        "folderId": 456,
        "companyId": 1,
        "parentId": 412,
        "folderNameShort": "R3456-EOE",
        "folderNameLong": "R3456-EOE",
        "folderDescription": null,
        "permissionLevelId": null,
        "permissionName": null,
        "permissionIcon": null,
        "userId": null,
        "userEmail": null,
        "accountGroupId": null,
        "accountGroupName": null,
        "image": "http://giblets-001-site2.dtempurl.com/images/icon/subfolder-database.png"
    },
    {
        "folderId": 457,
        "companyId": 1,
        "parentId": 429,
        "folderNameShort": "R272-CL",
        "folderNameLong": "R272-CL Long Name",
        "folderDescription": "R272-CL Description",
        "permissionLevelId": null,
        "permissionName": null,
        "permissionIcon": null,
        "userId": null,
        "userEmail": null,
        "accountGroupId": null,
        "accountGroupName": null,
        "image": "http://giblets-001-site2.dtempurl.com/images/icon/subfolder-database.png"
    },
    {
        "folderId": 459,
        "companyId": 1,
        "parentId": 443,
        "folderNameShort": "R4891-DIA",
        "folderNameLong": "R4891-DIA",
        "folderDescription": null,
        "permissionLevelId": null,
        "permissionName": null,
        "permissionIcon": null,
        "userId": null,
        "userEmail": null,
        "accountGroupId": null,
        "accountGroupName": null,
        "image": "http://giblets-001-site2.dtempurl.com/images/icon/subfolder-database.png"
    }
];
export default iconJson;