const demoData = 
[
    {
      "folderId": 2,
      "companyId": 1,
      "parentId": null,
      "folderNameShort": "Regeneron",
      "folderNameLong": "Regeneron Folder",
      "folderDescription": 'Regeneron Folder Content',
      "permissionLevelId": 2,
      "permissionName": "WRITE",
      "permissionIcon": "edit.png",
      "userId": 1,
      "userEmail": "mr.toshio.kimura@gmail.com",
      "accountGroupId": null,
      "accountGroupName": null,
      "image": "/images/icon/parameter-database.png"
    },
    {
      "folderId": 3,
      "companyId": 1,
      "parentId": 2,
      "folderNameShort": "BDM",
      "folderNameLong": "BDM Folder",
      "folderDescription": null,
      "permissionLevelId": null,
      "permissionName": null,
      "permissionIcon": null,
      "userId": null,
      "userEmail": null,
      "accountGroupId": null,
      "accountGroupName": null,
      "image": "/images/icon/subfolder-database.png"
    },
    {
      "folderId": 7,
      "companyId": 1,
      "parentId": 2,
      "folderNameShort": "Medical Affairs",
      "folderNameLong": "Medical Affairs Folder",
      "folderDescription": null,
      "permissionLevelId": null,
      "permissionName": null,
      "permissionIcon": null,
      "userId": null,
      "userEmail": null,
      "accountGroupId": null,
      "accountGroupName": null,
      "image": "/images/icon/subfolder-database.png"
    },
    {
      "folderId": 17,
      "companyId": 1,
      "parentId": 2,
      "folderNameShort": "PK",
      "folderNameLong": "PK Folder",
      "folderDescription": null,
      "permissionLevelId": null,
      "permissionName": null,
      "permissionIcon": null,
      "userId": null,
      "userEmail": null,
      "accountGroupId": null,
      "accountGroupName": null,
      "image": "/images/icon/subfolder-database.png"
    },
    {
      "folderId": 384,
      "companyId": 1,
      "parentId": null,
      "folderNameShort": "Immunology",
      "folderNameLong": "Immunology",
      "folderDescription": null,
      "permissionLevelId": 4,
      "permissionName": "DENY",
      "permissionIcon": "denyicon.png",
      "userId": 1,
      "userEmail": "mr.toshio.kimura@gmail.com",
      "accountGroupId": null,
      "accountGroupName": null,
      "image": "/images/icon/parameter-database.png"
    },
    {
      "folderId": 385,
      "companyId": 1,
      "parentId": null,
      "folderNameShort": "Ophthamology",
      "folderNameLong": "Ophthamology",
      "folderDescription": null,
      "permissionLevelId": 1,
      "permissionName": "READ",
      "permissionIcon": "view.png",
      "userId": 1,
      "userEmail": "mr.toshio.kimura@gmail.com",
      "accountGroupId": null,
      "accountGroupName": null,
      "image": "/images/icon/subfolder-database.png"
    },
    {
      "folderId": 386,
      "companyId": 1,
      "parentId": null,
      "folderNameShort": "Oncology",
      "folderNameLong": "Oncology",
      "folderDescription": null,
      "permissionLevelId": 3,
      "permissionName": "FULL",
      "permissionIcon": "unlockiconblack.png",
      "userId": 1,
      "userEmail": "mr.toshio.kimura@gmail.com",
      "accountGroupId": null,
      "accountGroupName": null,
      "image": "/images/icon/subfolder-database.png"
    },
    {
      "folderId": 387,
      "companyId": 1,
      "parentId": null,
      "folderNameShort": "General Medicine",
      "folderNameLong": "General Medicine",
      "folderDescription": null,
      "permissionLevelId": 4,
      "permissionName": "DENY",
      "permissionIcon": "denyicon.png",
      "userId": 1,
      "userEmail": "mr.toshio.kimura@gmail.com",
      "accountGroupId": null,
      "accountGroupName": null,
      "image": "/images/icon/subfolder-database.png"
    },
    {
      "folderId": 388,
      "companyId": 1,
      "parentId": 384,
      "folderNameShort": "R1234",
      "folderNameLong": "R1234",
      "folderDescription": null,
      "permissionLevelId": null,
      "permissionName": null,
      "permissionIcon": null,
      "userId": null,
      "userEmail": null,
      "accountGroupId": null,
      "accountGroupName": null,
      "image": "/images/icon/subfolder-database.png"
    },
    {
      "folderId": 412,
      "companyId": 1,
      "parentId": 384,
      "folderNameShort": "R3456",
      "folderNameLong": "R3456",
      "folderDescription": null,
      "permissionLevelId": null,
      "permissionName": null,
      "permissionIcon": null,
      "userId": null,
      "userEmail": null,
      "accountGroupId": null,
      "accountGroupName": null,
      "image": "/images/icon/subfolder-database.png"
    },
    {
      "folderId": 429,
      "companyId": 1,
      "parentId": 387,
      "folderNameShort": "R272",
      "folderNameLong": "R272",
      "folderDescription": null,
      "permissionLevelId": null,
      "permissionName": null,
      "permissionIcon": null,
      "userId": null,
      "userEmail": null,
      "accountGroupId": null,
      "accountGroupName": null,
      "image": "/images/icon/subfolder-database.png"
    },
    {
      "folderId": 443,
      "companyId": 1,
      "parentId": 386,
      "folderNameShort": "R4891",
      "folderNameLong": "R4891",
      "folderDescription": null,
      "permissionLevelId": null,
      "permissionName": null,
      "permissionIcon": null,
      "userId": null,
      "userEmail": null,
      "accountGroupId": null,
      "accountGroupName": null,
      "image": "/images/icon/subfolder-database.png"
    },
    {
      "folderId": 452,
      "companyId": 1,
      "parentId": 388,
      "folderNameShort": "R1234-AD",
      "folderNameLong": "R1234-AD",
      "folderDescription": null,
      "permissionLevelId": null,
      "permissionName": null,
      "permissionIcon": null,
      "userId": null,
      "userEmail": null,
      "accountGroupId": null,
      "accountGroupName": null,
      "image": "/images/icon/subfolder-database.png"
    },
    {
      "folderId": 453,
      "companyId": 1,
      "parentId": 388,
      "folderNameShort": "R1234-AS",
      "folderNameLong": "R1234-AS",
      "folderDescription": null,
      "permissionLevelId": null,
      "permissionName": null,
      "permissionIcon": null,
      "userId": null,
      "userEmail": null,
      "accountGroupId": null,
      "accountGroupName": null,
      "image": "/images/icon/subfolder-database.png"
    },
    {
      "folderId": 454,
      "companyId": 1,
      "parentId": 388,
      "folderNameShort": "R1234-NP",
      "folderNameLong": "R1234-NP",
      "folderDescription": null,
      "permissionLevelId": null,
      "permissionName": null,
      "permissionIcon": null,
      "userId": null,
      "userEmail": null,
      "accountGroupId": null,
      "accountGroupName": null,
      "image": "/images/icon/subfolder-database.png"
    },
    {
      "folderId": 455,
      "companyId": 1,
      "parentId": 412,
      "folderNameShort": "R3456-AS",
      "folderNameLong": "R3456-AS",
      "folderDescription": null,
      "permissionLevelId": null,
      "permissionName": null,
      "permissionIcon": null,
      "userId": null,
      "userEmail": null,
      "accountGroupId": null,
      "accountGroupName": null,
      "image": "/images/icon/subfolder-database.png"
    },
    {
      "folderId": 456,
      "companyId": 1,
      "parentId": 412,
      "folderNameShort": "R3456-EOE",
      "folderNameLong": "R3456-EOE",
      "folderDescription": null,
      "permissionLevelId": null,
      "permissionName": null,
      "permissionIcon": null,
      "userId": null,
      "userEmail": null,
      "accountGroupId": null,
      "accountGroupName": null,
      "image": "/images/icon/subfolder-database.png"
    },
    {
      "folderId": 457,
      "companyId": 1,
      "parentId": 429,
      "folderNameShort": "R272-CL",
      "folderNameLong": "R272-CL Long Name",
      "folderDescription": "R272-CL Description",
      "permissionLevelId": null,
      "permissionName": null,
      "permissionIcon": null,
      "userId": null,
      "userEmail": null,
      "accountGroupId": null,
      "accountGroupName": null,
      "image": "/images/icon/subfolder-database.png"
    },
    {
      "folderId": 459,
      "companyId": 1,
      "parentId": 443,
      "folderNameShort": "R4891-DIA",
      "folderNameLong": "R4891-DIA",
      "folderDescription": null,
      "permissionLevelId": null,
      "permissionName": null,
      "permissionIcon": null,
      "userId": null,
      "userEmail": null,
      "accountGroupId": null,
      "accountGroupName": null,
      "image": "/images/icon/subfolder-database.png"
    }
  ];

const sapData = [
  {
    "sapId": 4,
    "sapGuid": "BEBC20B8-42DB-4F0A-977B-B838C8874CE6",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": 22,
    "isFolder": false,
    "sapNameShort": "SAP 1 Short",
    "sapNameLong": "SAP 1 Long",
    "sapDescription": "SAP 1 Description",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 1,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 5,
    "sapGuid": "9B4152F5-7EF5-40CC-B1BC-AAFD51E96D9C",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": 22,
    "isFolder": false,
    "sapNameShort": "SAP 2 Short",
    "sapNameLong": "SAP 2 Long",
    "sapDescription": "SAP 2 Description",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 2,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 22,
    "sapGuid": "9E38BC67-4FC1-4601-8DB9-867D28BD22B6",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": null,
    "isFolder": false,
    "sapNameShort": "Phase 3",
    "sapNameLong": "TestSAPLongName_new",
    "sapDescription": "TestSAPDescription_new",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 9,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },

]
export const VariablesData = [
  {
    "sapId": 4,
    "sapGuid": "BEBC20B8-42DB-4F0A-977B-B838C8874CE6",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": 22,
    "isFolder": false,
    "sapNameShort": "SUBID",
    "sapNameLong": "SAP 1 Long",
    "sapDescription": "SAP 1 Description",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 1,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 5,
    "sapGuid": "9B4152F5-7EF5-40CC-B1BC-AAFD51E96D9C",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": 22,
    "isFolder": false,
    "sapNameShort": "USUBJID",
    "sapNameLong": "SAP 2 Long",
    "sapDescription": "SAP 2 Description",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 2,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 22,
    "sapGuid": "9E38BC67-4FC1-4601-8DB9-867D28BD22B6",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": null,
    "isFolder": false,
    "sapNameShort": "Subject",
    "sapNameLong": "TestSAPLongName_new",
    "sapDescription": "TestSAPDescription_new",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 9,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },

  {
    "sapId": 6,
    "sapGuid": "9E38BC67-4FC1-4601-8DB9-867D28BD22B6",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": null,
    "isFolder": false,
    "sapNameShort": "Study",
    "sapNameLong": "TestSAPLongName_new",
    "sapDescription": "TestSAPDescription_new",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 9,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 7,
    "sapGuid": "9E38BC67-4FC1-4601-8DB9-867D28BD22B6",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": null,
    "isFolder": false,
    "sapNameShort": "STUDYID",
    "sapNameLong": "TestSAPLongName_new",
    "sapDescription": "TestSAPDescription_new",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 9,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },

];
export const EndpointsData = [
  {
    "sapId": 4,
    "sapGuid": "BEBC20B8-42DB-4F0A-977B-B838C8874CE6",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": 22,
    "isFolder": false,
    "sapNameShort": "FEV1 : Forced expiratory volume in 1 second",
    "sapNameLong": "SAP 1 Long",
    "sapDescription": "SAP 1 Description",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 1,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 5,
    "sapGuid": "9B4152F5-7EF5-40CC-B1BC-AAFD51E96D9C",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": 22,
    "isFolder": false,
    "sapNameShort": "FVC : Forced Vital Capacity",
    "sapNameLong": "SAP 2 Long",
    "sapDescription": "SAP 2 Description",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 2,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 22,
    "sapGuid": "9E38BC67-4FC1-4601-8DB9-867D28BD22B6",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": null,
    "isFolder": false,
    "sapNameShort": "Pulmonary Function Test",
    "sapNameLong": "TestSAPLongName_new",
    "sapDescription": "TestSAPDescription_new",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 9,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },

]
export const analysisSet = [
  {
    "sapId": 4,
    "sapGuid": "BEBC20B8-42DB-4F0A-977B-B838C8874CE6",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": 22,
    "isFolder": false,
    "sapNameShort": "FEV1 : Forced expiratory volume in 1 second",
    "sapNameLong": "SAP 1 Long",
    "sapDescription": "SAP 1 Description",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 1,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 5,
    "sapGuid": "9B4152F5-7EF5-40CC-B1BC-AAFD51E96D9C",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": 22,
    "isFolder": false,
    "sapNameShort": "FVC : Forced Vital Capacity",
    "sapNameLong": "SAP 2 Long",
    "sapDescription": "SAP 2 Description",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 2,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 6,
    "sapGuid": "9B4152F5-7EF5-40CC-B1BC-AAFD51E96D9C",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": 23,
    "isFolder": false,
    "sapNameShort": "FVC : Forced Vital Capacity",
    "sapNameLong": "SAP 2 Long",
    "sapDescription": "SAP 2 Description",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 2,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 22,
    "sapGuid": "9E38BC67-4FC1-4601-8DB9-867D28BD22B6",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": null,
    "isFolder": false,
    "sapNameShort": "Efficacy",
    "sapNameLong": "TestSAPLongName_new",
    "sapDescription": "TestSAPDescription_new",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 9,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 23,
    "sapGuid": "9E38BC67-4FC1-4601-8DB9-867D28BD22B6",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": null,
    "isFolder": false,
    "sapNameShort": "Safety",
    "sapNameLong": "TestSAPLongName_new",
    "sapDescription": "TestSAPDescription_new",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 9,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },

]
export const Users_Permission = [
  {
    "sapId": 4,
    "sapGuid": "BEBC20B8-42DB-4F0A-977B-B838C8874CE6",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": 22,
    "isFolder": false,
    "sapAndRole": "SAP 1 Short",
    "sapNameLong": "SAP 1 Long",
    "sapDescription": "SAP 1 Description",
    "sapType": "Study SAP",
    "role": "Statistician",
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 1,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 5,
    "sapGuid": "9B4152F5-7EF5-40CC-B1BC-AAFD51E96D9C",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": 22,
    "isFolder": false,
    "sapAndRole": "SAP 2 Short",

    "sapNameLong": "SAP 2 Long",
    "sapDescription": "SAP 2 Description",
    "sapType": "Study SAP",
    "role" : "Statistician",

    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 2,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 6,
    "sapGuid": "9B4152F5-7EF5-40CC-B1BC-AAFD51E96D9C",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": 23,
    "isFolder": false,
    "sapAndRole": "SAP Short V1",
    "sapNameLong": "SAP 2 Long",
    "sapDescription": "SAP 2 Description",
    "sapAndRole": "SAP 2 Short",

    "sapTypeId": 381,
    "sapType": "Study SAP",
    "role" : "Statistician",
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 2,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 22,
    "sapGuid": "9E38BC67-4FC1-4601-8DB9-867D28BD22B6",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": null,
    "isFolder": false,
    "sapAndRole": "SAP Folder 123",
    "sapNameLong": "TestSAPLongName_new",
    "sapDescription": "TestSAPDescription_new",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 9,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 23,
    "sapGuid": "9E38BC67-4FC1-4601-8DB9-867D28BD22B6",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": null,
    "isFolder": false,
    "sapAndRole": "Test SAP",
    "sapNameLong": "TestSAPLongName_new",
    "sapDescription": "TestSAPDescription_new",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 9,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },

]
export const PassWordReset = [
  {
    "sapId": 4,
    "sapGuid": "BEBC20B8-42DB-4F0A-977B-B838C8874CE6",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": null,
    "isFolder": false,
    "loginAttemps": "2023-10-02, 10:57 am",
    "success" : 'Yes',
    "IP" : "xx.xx.xx.xx", 
    "sapNameLong": "SAP 1 Long",
    "sapDescription": "SAP 1 Description",
    "sapType": "Study SAP",
    "role": "Statistician",
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 1,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
]
export const LoginAtmp = [
  {
    "sapId": 4,
    "sapGuid": "BEBC20B8-42DB-4F0A-977B-B838C8874CE6",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": null,
    "isFolder": false,
    "loginAttemps": "2023-10-02, 10:57 am",
    "success" : 'Yes',
    "IP" : "xx.xx.xx.xx", 
    "sapNameLong": "SAP 1 Long",
    "sapDescription": "SAP 1 Description",
    "sapType": "Study SAP",
    "role": "Statistician",
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 1,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 5,
    "sapGuid": "9B4152F5-7EF5-40CC-B1BC-AAFD51E96D9C",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": null,
    "isFolder": false,
    "sapAndRole": "SAP 2 Short",
    "loginAttemps": "2023-10-01, 5:20 pm",
    "IP" : "xx.xx.xx.xx", 

    "success" : 'Yes',


    "sapNameLong": "SAP 2 Long",
    "sapDescription": "SAP 2 Description",
    "sapType": "Study SAP",
    "role" : "Statistician",

    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 2,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 6,
    "sapGuid": "9B4152F5-7EF5-40CC-B1BC-AAFD51E96D9C",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": null,
    "loginAttemps": "2023-09-29, 12:06 am",
    "success" : 'Yes',
    "IP" : "xx.xx.xx.xx", 


    "isFolder": false,
    "sapAndRole": "SAP Short V1",
    "sapNameLong": "SAP 2 Long",
    "sapDescription": "SAP 2 Description",
    "sapAndRole": "SAP 2 Short",

    "sapTypeId": 381,
    "sapType": "Study SAP",
    "role" : "Statistician",
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 2,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 22,
    "sapGuid": "9E38BC67-4FC1-4601-8DB9-867D28BD22B6",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": null,
    "loginAttemps": "2023-09-28, 9:31 pm",
    "success" : 'Yes',
    "IP" : "xx.xx.xx.xx", 

    "isFolder": false,
    "sapAndRole": "SAP Folder 123",
    "sapNameLong": "TestSAPLongName_new",
    "sapDescription": "TestSAPDescription_new",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 9,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  

]
export const treatments = [
  {
    "sapId": 4,
    "sapGuid": "BEBC20B8-42DB-4F0A-977B-B838C8874CE6",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": 22,
    "isFolder": false,
    "sapNameShort": "FEV1 : Forced expiratory volume in 1 second",
    "sapNameLong": "SAP 1 Long",
    "sapDescription": "SAP 1 Description",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 1,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 5,
    "sapGuid": "9B4152F5-7EF5-40CC-B1BC-AAFD51E96D9C",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": 22,
    "isFolder": false,
    "sapNameShort": "FVC : Forced Vital Capacity",
    "sapNameLong": "SAP 2 Long",
    "sapDescription": "SAP 2 Description",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 2,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 6,
    "sapGuid": "9B4152F5-7EF5-40CC-B1BC-AAFD51E96D9C",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": 23,
    "isFolder": false,
    "sapNameShort": "FVC : Forced Vital Capacity",
    "sapNameLong": "SAP 2 Long",
    "sapDescription": "SAP 2 Description",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 2,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 22,
    "sapGuid": "9E38BC67-4FC1-4601-8DB9-867D28BD22B6",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": null,
    "isFolder": false,
    "sapNameShort": "Efficacy",
    "sapNameLong": "TestSAPLongName_new",
    "sapDescription": "TestSAPDescription_new",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 9,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 23,
    "sapGuid": "9E38BC67-4FC1-4601-8DB9-867D28BD22B6",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": null,
    "isFolder": false,
    "sapNameShort": "Safety",
    "sapNameLong": "TestSAPLongName_new",
    "sapDescription": "TestSAPDescription_new",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 9,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },

]
export const visitStructure = [
  {
    "sapId": 4,
    "sapGuid": "BEBC20B8-42DB-4F0A-977B-B838C8874CE6",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": 22,
    "isFolder": false,
    "sapNameShort": "Visit 1 : screening visit",
    "sapNameLong": "SAP 1 Long",
    "sapDescription": "SAP 1 Description",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 1,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 5,
    "sapGuid": "9B4152F5-7EF5-40CC-B1BC-AAFD51E96D9C",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": 22,
    "isFolder": false,
    "sapNameShort": "Visit 2 : Baseline visit",
    "sapNameLong": "SAP 2 Long",
    "sapDescription": "SAP 2 Description",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 2,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 6,
    "sapGuid": "9B4152F5-7EF5-40CC-B1BC-AAFD51E96D9C",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": 23,
    "isFolder": false,
    "sapNameShort": "Visit 3 : Week 4",
    "sapNameLong": "SAP 2 Long",
    "sapDescription": "SAP 2 Description",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 2,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 22,
    "sapGuid": "9E38BC67-4FC1-4601-8DB9-867D28BD22B6",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": null,
    "isFolder": false,
    "sapNameShort": "Period 1 : Screening Period",
    "sapNameLong": "TestSAPLongName_new",
    "sapDescription": "TestSAPDescription_new",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 9,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 23,
    "sapGuid": "9E38BC67-4FC1-4601-8DB9-867D28BD22B6",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": null,
    "isFolder": false,
    "sapNameShort": "Period 2 : Double-blind Period",
    "sapNameLong": "TestSAPLongName_new",
    "sapDescription": "TestSAPDescription_new",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 9,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },

]
export const visitFlag = [
  {
    "sapId": 22,
    "sapGuid": "9E38BC67-4FC1-4601-8DB9-867D28BD22B6",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": null,
    "isFolder": false,
    "sapNameShort": "All Visits",
    "sapNameLong": "TestSAPLongName_new",
    "sapDescription": "TestSAPDescription_new",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 9,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 23,
    "sapGuid": "9E38BC67-4FC1-4601-8DB9-867D28BD22B6",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": null,
    "isFolder": false,
    "sapNameShort": "Randomised DB Period",
    "sapNameLong": "TestSAPLongName_new",
    "sapDescription": "TestSAPDescription_new",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 9,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },
  {
    "sapId": 24,
    "sapGuid": "9E38BC67-4FC1-4601-8DB9-867D28BD22B6",
    "contentTypeId": 0,
    "companyId": 1,
    "parentId": null,
    "isFolder": false,
    "sapNameShort": "Follow-up Period",
    "sapNameLong": "TestSAPLongName_new",
    "sapDescription": "TestSAPDescription_new",
    "sapTypeId": 381,
    "sapTypeName": "CSR Final Analysis",
    "displayOrder": 9,
    "sapVersionNumber": null,
    "sapVersionDate": "0001-01-01T00:00:00",
    "sapVersionNameShort": null,
    "sapVersionNameLong": null,
    "sapVersionDescription": null
  },

]
export default sapData