const standardComponent = [
  {
    standardIconId: 1,
    companyId: 1,
    standardIconNameShort: "Category Data",
    standardIconNameLong: null,
    standardIconLabel: "Data",
    standardIcon: "images/icon/folder-database.png",
    iconTypeId: 1,
    standardIconOrder: 1,
  },
  {
    standardIconId: 23,
    companyId: 1,
    standardIconNameShort: "Category Endpoint",
    standardIconNameLong: null,
    standardIconLabel: "Endpoint",
    standardIcon: "images/icon/folder-stethoscope1-1.png",
    iconTypeId: 1,
    standardIconOrder: 2,
  },
  {
    standardIconId: 3,
    companyId: 1,
    standardIconNameShort: "Category Analysis",
    standardIconNameLong: null,
    standardIconLabel: "Analysis",
    standardIcon: "images/icon/folder-analysis.png",
    iconTypeId: 1,
    standardIconOrder: 3,
  },
  {
    standardIconId: 5,
    companyId: 1,
    standardIconNameShort: "Category Output",
    standardIconNameLong: null,
    standardIconLabel: "Output",
    standardIcon: "images/icon/folder-output.png",
    iconTypeId: 1,
    standardIconOrder: 4,
  },
  {
    standardIconId: 6,
    companyId: 1,
    standardIconNameShort: "Category Admin",
    standardIconNameLong: null,
    standardIconLabel: "Admin",
    standardIcon: "images/icon/folder-admin.png",
    iconTypeId: 1,
    standardIconOrder: 5,
  },
  {
    standardIconId: 7,
    companyId: 1,
    standardIconNameShort: "Category Other",
    standardIconNameLong: null,
    standardIconLabel: "Other",
    standardIcon: "images/nodetype/folder_32.png",
    iconTypeId: 1,
    standardIconOrder: 6,
  },
  {
    standardIconId: 17,
    companyId: 1,
    standardIconNameShort: "SubCategory Data",
    standardIconNameLong: null,
    standardIconLabel: "Data",
    standardIcon: "images/icon/subfolder-database.png",
    iconTypeId: 2,
    standardIconOrder: 1,
  },
  {
    standardIconId: 25,
    companyId: 1,
    standardIconNameShort: "SubCategory Endpoint",
    standardIconNameLong: null,
    standardIconLabel: "Endpoint",
    standardIcon: "images/icon/subfolder-stethoscope1-1.png",
    iconTypeId: 2,
    standardIconOrder: 2,
  },
  {
    standardIconId: 18,
    companyId: 1,
    standardIconNameShort: "SubCategory Analysis",
    standardIconNameLong: null,
    standardIconLabel: "Analysis",
    standardIcon: "images/icon/subfolder-analysis.png",
    iconTypeId: 2,
    standardIconOrder: 3,
  },
  {
    standardIconId: 19,
    companyId: 1,
    standardIconNameShort: "SubCategory Output",
    standardIconNameLong: null,
    standardIconLabel: "Output",
    standardIcon: "images/icon/subfolder-output.png",
    iconTypeId: 2,
    standardIconOrder: 4,
  },
  {
    standardIconId: 20,
    companyId: 1,
    standardIconNameShort: "SubCategory Admin",
    standardIconNameLong: null,
    standardIconLabel: "Admin",
    standardIcon: "images/icon/subfolder-admin.png",
    iconTypeId: 2,
    standardIconOrder: 5,
  },
  {
    standardIconId: 21,
    companyId: 1,
    standardIconNameShort: "SubCategory Other",
    standardIconNameLong: null,
    standardIconLabel: "Other",
    standardIcon: "images/icon/subfolder-yellow.png",
    iconTypeId: 2,
    standardIconOrder: 6,
  },
  {
    standardIconId: 9,
    companyId: 1,
    standardIconNameShort: "Parameter Data",
    standardIconNameLong: null,
    standardIconLabel: "Data",
    standardIcon: "images/icon/parameter-database.png",
    iconTypeId: 3,
    standardIconOrder: 1,
  },
  {
    standardIconId: 26,
    companyId: 1,
    standardIconNameShort: "Parameter Endpoint",
    standardIconNameLong: null,
    standardIconLabel: "Endpoint",
    standardIcon: "images/icon/stethoscope1.png",
    iconTypeId: 3,
    standardIconOrder: 2,
  },
  {
    standardIconId: 10,
    companyId: 1,
    standardIconNameShort: "Parameter Analysis",
    standardIconNameLong: null,
    standardIconLabel: "Analysis",
    standardIcon: "images/icon/parameter-analysis.png",
    iconTypeId: 3,
    standardIconOrder: 3,
  },
  {
    standardIconId: 14,
    companyId: 1,
    standardIconNameShort: "Parameter Output",
    standardIconNameLong: null,
    standardIconLabel: "Output",
    standardIcon: "images/icon/parameter-output.png",
    iconTypeId: 3,
    standardIconOrder: 4,
  },
  {
    standardIconId: 15,
    companyId: 1,
    standardIconNameShort: "Parameter Admin",
    standardIconNameLong: null,
    standardIconLabel: "Admin",
    standardIcon: "images/icon/parameter-admin.png",
    iconTypeId: 3,
    standardIconOrder: 5,
  },
  {
    standardIconId: 16,
    companyId: 1,
    standardIconNameShort: "Parameter Other",
    standardIconNameLong: null,
    standardIconLabel: "Other",
    standardIcon: "images/icon/parameter-text-number.png",
    iconTypeId: 3,
    standardIconOrder: 6,
  },
  {
    standardIconId: 27,
    companyId: 1,
    standardIconNameShort: "Character String",
    standardIconNameLong: null,
    standardIconLabel: "Character String",
    standardIcon: "images/icon/textbox-input-1.png",
    iconTypeId: 4,
    standardIconOrder: 1,
  },
  {
    standardIconId: 28,
    companyId: 1,
    standardIconNameShort: "Number",
    standardIconNameLong: null,
    standardIconLabel: "Number",
    standardIcon: "images/icon/number-box.png",
    iconTypeId: 4,
    standardIconOrder: 3,
  },
  {
    standardIconId: 29,
    companyId: 1,
    standardIconNameShort: "Controlled Terminology",
    standardIconNameLong: null,
    standardIconLabel: "Controlled Terminology",
    standardIcon: "images/icon/drop-down-list-1.png",
    iconTypeId: 4,
    standardIconOrder: 4,
  },
  {
    standardIconId: 30,
    companyId: 1,
    standardIconNameShort: "Dataset",
    standardIconNameLong: null,
    standardIconLabel: "Dataset",
    standardIcon: "images/icon/parameter-database.png",
    iconTypeId: 4,
    standardIconOrder: 5,
  },
  {
    standardIconId: 31,
    companyId: 1,
    standardIconNameShort: "Dataset Variable",
    standardIconNameLong: null,
    standardIconLabel: "Dataset Variable",
    standardIcon: "images/icon/table-select-column-1.png",
    iconTypeId: 4,
    standardIconOrder: 6,
  },
  {
    standardIconId: 32,
    companyId: 1,
    standardIconNameShort: "Variable Value",
    standardIconNameLong: null,
    standardIconLabel: "Variable Value",
    standardIcon: "images/icon/table-select-cell-1.png",
    iconTypeId: 4,
    standardIconOrder: 7,
  },
  {
    standardIconId: 33,
    companyId: 1,
    standardIconNameShort: "SubParameter Data",
    standardIconNameLong: null,
    standardIconLabel: "Data",
    standardIcon: "images/icon/parameter-database-sub.png",
    iconTypeId: 5,
    standardIconOrder: 1,
  },
  {
    standardIconId: 34,
    companyId: 1,
    standardIconNameShort: "SubParameter Endpoint",
    standardIconNameLong: null,
    standardIconLabel: "Endpoint",
    standardIcon: "images/icon/stethoscope1-sub.png",
    iconTypeId: 5,
    standardIconOrder: 2,
  },
  {
    standardIconId: 35,
    companyId: 1,
    standardIconNameShort: "SubParameter Analysis",
    standardIconNameLong: null,
    standardIconLabel: "Analysis",
    standardIcon: "images/icon/parameter-analysis-sub.png",
    iconTypeId: 5,
    standardIconOrder: 3,
  },
  {
    standardIconId: 36,
    companyId: 1,
    standardIconNameShort: "SubParameter Output",
    standardIconNameLong: null,
    standardIconLabel: "Output",
    standardIcon: "images/icon/parameter-output-sub.png",
    iconTypeId: 5,
    standardIconOrder: 4,
  },
  {
    standardIconId: 37,
    companyId: 1,
    standardIconNameShort: "SubParameter Admin",
    standardIconNameLong: null,
    standardIconLabel: "Admin",
    standardIcon: "images/icon/parameter-admin-sub.png",
    iconTypeId: 5,
    standardIconOrder: 5,
  },
];
export default standardComponent