
export const TerminologyCode  = [
    {
      "libraryControlledTerminologyId": 1,
      "libraryControlledTerminologyGuid": "F6F7E6B4-742E-4035-A5D6-705C33AA47CD",
      "libraryControlledTerminologyCategoryId": 1,
      "parentId": null,
      "isFolder": false,
      "libraryControlledTerminologyNameShort": "UN",
      "libraryControlledTerminologyNameLong": "Unstructured",
      "libraryControlledTerminologyDescription": "Unstructured",
      "isCustom": false,
      "isHidden": false,
      "displayOrder": 1
    },
    {
      "libraryControlledTerminologyId": 2,
      "libraryControlledTerminologyGuid": "A9BDB122-8FC4-4581-94D8-B10B9CB38C8D",
      "libraryControlledTerminologyCategoryId": 1,
      "parentId": null,
      "isFolder": false,
      "libraryControlledTerminologyNameShort": "CS",
      "libraryControlledTerminologyNameLong": "Compound symmetry",
      "libraryControlledTerminologyDescription": "Compound symmetry",
      "isCustom": false,
      "isHidden": false,
      "displayOrder": 2
    },
    {
      "libraryControlledTerminologyId": 3,
      "libraryControlledTerminologyGuid": "75C94661-B1BC-48CC-ACBC-94AE33629B1D",
      "libraryControlledTerminologyCategoryId": 1,
      "parentId": null,
      "isFolder": false,
      "libraryControlledTerminologyNameShort": "VC",
      "libraryControlledTerminologyNameLong": "Variance components",
      "libraryControlledTerminologyDescription": "Variance components",
      "isCustom": false,
      "isHidden": false,
      "displayOrder": 3
    },
    {
      "libraryControlledTerminologyId": 4,
      "libraryControlledTerminologyGuid": "2F015552-32F5-48ED-804B-9691C60C21C4",
      "libraryControlledTerminologyCategoryId": 1,
      "parentId": null,
      "isFolder": false,
      "libraryControlledTerminologyNameShort": "AR(1)",
      "libraryControlledTerminologyNameLong": "Autoregressive(1)",
      "libraryControlledTerminologyDescription": "Autoregressive(1)",
      "isCustom": false,
      "isHidden": false,
      "displayOrder": 4
    },
    {
      "libraryControlledTerminologyId": 5,
      "libraryControlledTerminologyGuid": "89AAE93E-BC38-42A1-9262-4C037570DB62",
      "libraryControlledTerminologyCategoryId": 1,
      "parentId": null,
      "isFolder": false,
      "libraryControlledTerminologyNameShort": "CSH",
      "libraryControlledTerminologyNameLong": "Heterogeneous CS",
      "libraryControlledTerminologyDescription": "Heterogeneous CS",
      "isCustom": false,
      "isHidden": false,
      "displayOrder": 5
    },
    {
      "libraryControlledTerminologyId": 6,
      "libraryControlledTerminologyGuid": "15B04D49-13C3-4392-8901-9288E3A64590",
      "libraryControlledTerminologyCategoryId": 1,
      "parentId": null,
      "isFolder": false,
      "libraryControlledTerminologyNameShort": "ANTE(1)",
      "libraryControlledTerminologyNameLong": "Antedependence",
      "libraryControlledTerminologyDescription": "Antedependence",
      "isCustom": false,
      "isHidden": false,
      "displayOrder": 6
    },
    {
      "libraryControlledTerminologyId": 7,
      "libraryControlledTerminologyGuid": "ED180C2B-440B-411F-A78B-D34438322902",
      "libraryControlledTerminologyCategoryId": 1,
      "parentId": null,
      "isFolder": false,
      "libraryControlledTerminologyNameShort": "ARMA(1,1)",
      "libraryControlledTerminologyNameLong": "ARMA(1,1)",
      "libraryControlledTerminologyDescription": "ARMA(1,1)",
      "isCustom": false,
      "isHidden": false,
      "displayOrder": 7
    },
    {
      "libraryControlledTerminologyId": 8,
      "libraryControlledTerminologyGuid": "05E85D32-E0A0-4887-B05D-831CE55DE9DC",
      "libraryControlledTerminologyCategoryId": 1,
      "parentId": null,
      "isFolder": false,
      "libraryControlledTerminologyNameShort": "HF",
      "libraryControlledTerminologyNameLong": "Huynh-Feldt",
      "libraryControlledTerminologyDescription": "Huynh-Feldt",
      "isCustom": false,
      "isHidden": false,
      "displayOrder": 8
    },
    {
      "libraryControlledTerminologyId": 9,
      "libraryControlledTerminologyGuid": "DBE7D999-11F4-4272-9D05-73A1C9FD5118",
      "libraryControlledTerminologyCategoryId": 1,
      "parentId": null,
      "isFolder": false,
      "libraryControlledTerminologyNameShort": "TOEP",
      "libraryControlledTerminologyNameLong": "Toeplitz",
      "libraryControlledTerminologyDescription": "Toeplitz",
      "isCustom": false,
      "isHidden": false,
      "displayOrder": 9
    },
    {
      "libraryControlledTerminologyId": 10,
      "libraryControlledTerminologyGuid": "4FAEE69B-83AC-4EEE-B055-A46A78197DA6",
      "libraryControlledTerminologyCategoryId": 1,
      "parentId": null,
      "isFolder": false,
      "libraryControlledTerminologyNameShort": "TOEPH",
      "libraryControlledTerminologyNameLong": "Heterogeneous TOEP",
      "libraryControlledTerminologyDescription": "Heterogeneous TOEP",
      "isCustom": false,
      "isHidden": false,
      "displayOrder": 10
    },
    {
      "libraryControlledTerminologyId": 11,
      "libraryControlledTerminologyGuid": "3446834E-FACA-4595-8844-57ADAB4DC244",
      "libraryControlledTerminologyCategoryId": 1,
      "parentId": null,
      "isFolder": false,
      "libraryControlledTerminologyNameShort": "UNR",
      "libraryControlledTerminologyNameLong": "Unstructured corrs",
      "libraryControlledTerminologyDescription": "Unstructured corrs",
      "isCustom": false,
      "isHidden": false,
      "displayOrder": 11
    },
    {
      "libraryControlledTerminologyId": 12,
      "libraryControlledTerminologyGuid": "19B18DD5-E036-4395-9EDC-E0122F5AF1C1",
      "libraryControlledTerminologyCategoryId": 1,
      "parentId": null,
      "isFolder": false,
      "libraryControlledTerminologyNameShort": "UN@AR(1)",
      "libraryControlledTerminologyNameLong": "Direct product AR(1)",
      "libraryControlledTerminologyDescription": "Direct product AR(1)",
      "isCustom": false,
      "isHidden": false,
      "displayOrder": 12
    },
    {
      "libraryControlledTerminologyId": 13,
      "libraryControlledTerminologyGuid": "D91B28E1-D5EB-455A-80AD-4E0DC5B46085",
      "libraryControlledTerminologyCategoryId": 1,
      "parentId": null,
      "isFolder": false,
      "libraryControlledTerminologyNameShort": "UN@CS",
      "libraryControlledTerminologyNameLong": "Direct product CS",
      "libraryControlledTerminologyDescription": "Direct product CS",
      "isCustom": false,
      "isHidden": false,
      "displayOrder": 13
    },
    {
      "libraryControlledTerminologyId": 14,
      "libraryControlledTerminologyGuid": "CD3F06D8-1403-43CD-B485-57CB7840A05E",
      "libraryControlledTerminologyCategoryId": 2,
      "parentId": null,
      "isFolder": false,
      "libraryControlledTerminologyNameShort": "REML",
      "libraryControlledTerminologyNameLong": "Restricted maximum likelihood",
      "libraryControlledTerminologyDescription": "Restricted maximum likelihood",
      "isCustom": false,
      "isHidden": false,
      "displayOrder": 5
    },
    {
      "libraryControlledTerminologyId": 15,
      "libraryControlledTerminologyGuid": "49F64722-8D36-406E-9571-352E05A1D3E0",
      "libraryControlledTerminologyCategoryId": 2,
      "parentId": null,
      "isFolder": false,
      "libraryControlledTerminologyNameShort": "ML",
      "libraryControlledTerminologyNameLong": "Maximum likelihood",
      "libraryControlledTerminologyDescription": "Maximum likelihood",
      "isCustom": false,
      "isHidden": false,
      "displayOrder": 6
    },
    {
      "libraryControlledTerminologyId": 16,
      "libraryControlledTerminologyGuid": "7578ACF4-4067-448E-9BF2-56A5C32DEC12",
      "libraryControlledTerminologyCategoryId": 2,
      "parentId": null,
      "isFolder": false,
      "libraryControlledTerminologyNameShort": "MIVQUE0",
      "libraryControlledTerminologyNameLong": "Minimum variance quadratic unbiased estimation",
      "libraryControlledTerminologyDescription": "Minimum variance quadratic unbiased estimation",
      "isCustom": false,
      "isHidden": false,
      "displayOrder": 2
    },
    {
      "libraryControlledTerminologyId": 17,
      "libraryControlledTerminologyGuid": "FD2805BA-72B1-43BE-8A3D-C02B528BE4BA",
      "libraryControlledTerminologyCategoryId": 2,
      "parentId": null,
      "isFolder": false,
      "libraryControlledTerminologyNameShort": "TYPE1",
      "libraryControlledTerminologyNameLong": "TYPE1",
      "libraryControlledTerminologyDescription": "TYPE1",
      "isCustom": false,
      "isHidden": false,
      "displayOrder": 3
    },
    {
      "libraryControlledTerminologyId": 18,
      "libraryControlledTerminologyGuid": "B109925E-D88A-4FB5-9DBF-E2F9F3E343E8",
      "libraryControlledTerminologyCategoryId": 2,
      "parentId": null,
      "isFolder": false,
      "libraryControlledTerminologyNameShort": "TYPE2",
      "libraryControlledTerminologyNameLong": "TYPE2",
      "libraryControlledTerminologyDescription": "TYPE2",
      "isCustom": false,
      "isHidden": false,
      "displayOrder": 4
    },
    {
      "libraryControlledTerminologyId": 19,
      "libraryControlledTerminologyGuid": "CCFA05CC-4241-446E-B5E3-5A590BB25602",
      "libraryControlledTerminologyCategoryId": 2,
      "parentId": null,
      "isFolder": false,
      "libraryControlledTerminologyNameShort": "TYPE3",
      "libraryControlledTerminologyNameLong": "TYPE3",
      "libraryControlledTerminologyDescription": "TYPE3",
      "isCustom": false,
      "isHidden": false,
      "displayOrder": 1
    },
    {
      "libraryControlledTerminologyId": 20,
      "libraryControlledTerminologyGuid": "DE90DF4B-151F-46FC-ADD4-BD2FCE25C6E5",
      "libraryControlledTerminologyCategoryId": 3,
      "parentId": null,
      "isFolder": false,
      "libraryControlledTerminologyNameShort": "SAT",
      "libraryControlledTerminologyNameLong": "Satterthwaite",
      "libraryControlledTerminologyDescription": "Satterthwaite",
      "isCustom": false,
      "isHidden": false,
      "displayOrder": 1
    },
    {
      "libraryControlledTerminologyId": 21,
      "libraryControlledTerminologyGuid": "FC15B4F7-94B9-48C9-93D2-0791863CB82D",
      "libraryControlledTerminologyCategoryId": 3,
      "parentId": null,
      "isFolder": false,
      "libraryControlledTerminologyNameShort": "KR",
      "libraryControlledTerminologyNameLong": "Kenward Roger",
      "libraryControlledTerminologyDescription": "Kenward Roger",
      "isCustom": false,
      "isHidden": false,
      "displayOrder": 2
    },
    {
      "libraryControlledTerminologyId": 22,
      "libraryControlledTerminologyGuid": "0BE9FD2C-8332-4EE0-BE80-90F06DE41EDF",
      "libraryControlledTerminologyCategoryId": 3,
      "parentId": null,
      "isFolder": false,
      "libraryControlledTerminologyNameShort": "BW",
      "libraryControlledTerminologyNameLong": "BETWITHIN",
      "libraryControlledTerminologyDescription": "BETWITHIN",
      "isCustom": false,
      "isHidden": false,
      "displayOrder": 3
    },
    {
      "libraryControlledTerminologyId": 23,
      "libraryControlledTerminologyGuid": "EBC74525-FF39-4164-BE07-07F557D52E10",
      "libraryControlledTerminologyCategoryId": 3,
      "parentId": null,
      "isFolder": false,
      "libraryControlledTerminologyNameShort": "CON",
      "libraryControlledTerminologyNameLong": "Contain",
      "libraryControlledTerminologyDescription": "Contain",
      "isCustom": false,
      "isHidden": false,
      "displayOrder": 4
    },
    {
      "libraryControlledTerminologyId": 24,
      "libraryControlledTerminologyGuid": "B9B8835F-2ACC-4C9D-A2E3-801FDDF2483A",
      "libraryControlledTerminologyCategoryId": 3,
      "parentId": null,
      "isFolder": false,
      "libraryControlledTerminologyNameShort": "RES",
      "libraryControlledTerminologyNameLong": "Residual",
      "libraryControlledTerminologyDescription": "Residual",
      "isCustom": false,
      "isHidden": false,
      "displayOrder": 5
    },
    {
    "libraryControlledTerminologyId": 20,
    "libraryControlledTerminologyGuid": "DE90DF4B-151F-46FC-ADD4-BD2FCE25C6E5",
    "libraryControlledTerminologyCategoryId": 3,
    "parentId": null,
    "isFolder": false,
    "libraryControlledTerminologyNameShort": "SAT",
    "libraryControlledTerminologyNameLong": "Satterthwaite",
    "libraryControlledTerminologyDescription": "Satterthwaite",
    "isCustom": false,
    "isHidden": false,
    "displayOrder": 1
  },
  {
    "libraryControlledTerminologyId": 21,
    "libraryControlledTerminologyGuid": "FC15B4F7-94B9-48C9-93D2-0791863CB82D",
    "libraryControlledTerminologyCategoryId": 3,
    "parentId": null,
    "isFolder": false,
    "libraryControlledTerminologyNameShort": "KR",
    "libraryControlledTerminologyNameLong": "Kenward Roger",
    "libraryControlledTerminologyDescription": "Kenward Roger",
    "isCustom": false,
    "isHidden": false,
    "displayOrder": 2
  },
  {
    "libraryControlledTerminologyId": 22,
    "libraryControlledTerminologyGuid": "0BE9FD2C-8332-4EE0-BE80-90F06DE41EDF",
    "libraryControlledTerminologyCategoryId": 3,
    "parentId": null,
    "isFolder": false,
    "libraryControlledTerminologyNameShort": "BW",
    "libraryControlledTerminologyNameLong": "BETWITHIN",
    "libraryControlledTerminologyDescription": "BETWITHIN",
    "isCustom": false,
    "isHidden": false,
    "displayOrder": 3
  },
  {
    "libraryControlledTerminologyId": 23,
    "libraryControlledTerminologyGuid": "EBC74525-FF39-4164-BE07-07F557D52E10",
    "libraryControlledTerminologyCategoryId": 3,
    "parentId": null,
    "isFolder": false,
    "libraryControlledTerminologyNameShort": "CON",
    "libraryControlledTerminologyNameLong": "Contain",
    "libraryControlledTerminologyDescription": "Contain",
    "isCustom": false,
    "isHidden": false,
    "displayOrder": 4
  },
  {
    "libraryControlledTerminologyId": 24,
    "libraryControlledTerminologyGuid": "B9B8835F-2ACC-4C9D-A2E3-801FDDF2483A",
    "libraryControlledTerminologyCategoryId": 3,
    "parentId": null,
    "isFolder": false,
    "libraryControlledTerminologyNameShort": "RES",
    "libraryControlledTerminologyNameLong": "Residual",
    "libraryControlledTerminologyDescription": "Residual",
    "isCustom": false,
    "isHidden": false,
    "displayOrder": 5
  },
  {
    "libraryControlledTerminologyId": 49,
    "libraryControlledTerminologyGuid": "0FEED490-AF77-495C-8FD1-FAFB790FB9F7",
    "libraryControlledTerminologyCategoryId": 10,
    "parentId": null,
    "isFolder": false,
    "libraryControlledTerminologyNameShort": "Continuous",
    "libraryControlledTerminologyNameLong": "Continuous",
    "libraryControlledTerminologyDescription": "Continuous",
    "isCustom": false,
    "isHidden": false,
    "displayOrder": 2
  },
  {
    "libraryControlledTerminologyId": 50,
    "libraryControlledTerminologyGuid": "BA68F87B-83B0-4B20-A9D2-D1D920BC40C6",
    "libraryControlledTerminologyCategoryId": 10,
    "parentId": null,
    "isFolder": false,
    "libraryControlledTerminologyNameShort": "Binary",
    "libraryControlledTerminologyNameLong": "Binary",
    "libraryControlledTerminologyDescription": "Binary",
    "isCustom": false,
    "isHidden": false,
    "displayOrder": 1
  },
  {
    "libraryControlledTerminologyId": 51,
    "libraryControlledTerminologyGuid": "B2087255-490B-4C77-9F8F-13A91C93E241",
    "libraryControlledTerminologyCategoryId": 10,
    "parentId": null,
    "isFolder": false,
    "libraryControlledTerminologyNameShort": "Categorical",
    "libraryControlledTerminologyNameLong": "Categorical",
    "libraryControlledTerminologyDescription": "Categorical",
    "isCustom": false,
    "isHidden": false,
    "displayOrder": 3
  },
  {
    "libraryControlledTerminologyId": 52,
    "libraryControlledTerminologyGuid": "4257D16C-EEF2-404A-9624-0A6CB4C46784",
    "libraryControlledTerminologyCategoryId": 10,
    "parentId": null,
    "isFolder": false,
    "libraryControlledTerminologyNameShort": "Count",
    "libraryControlledTerminologyNameLong": "Count",
    "libraryControlledTerminologyDescription": "Count",
    "isCustom": false,
    "isHidden": false,
    "displayOrder": 5
  },
  {
    "libraryControlledTerminologyId": 53,
    "libraryControlledTerminologyGuid": "454842D3-3803-4CD2-ABBF-8D3F6C797CAD",
    "libraryControlledTerminologyCategoryId": 10,
    "parentId": null,
    "isFolder": false,
    "libraryControlledTerminologyNameShort": "Time-to-Event",
    "libraryControlledTerminologyNameLong": "Time-to-Event",
    "libraryControlledTerminologyDescription": "Time-to-Event",
    "isCustom": false,
    "isHidden": false,
    "displayOrder": 4
  },
  {
    "libraryControlledTerminologyId": 198,
    "libraryControlledTerminologyGuid": "5698438A-B07A-40A3-AF00-939C24F576D2",
    "libraryControlledTerminologyCategoryId": 10,
    "parentId": null,
    "isFolder": false,
    "libraryControlledTerminologyNameShort": "Text",
    "libraryControlledTerminologyNameLong": "Text",
    "libraryControlledTerminologyDescription": "Text",
    "isCustom": false,
    "isHidden": false,
    "displayOrder": 6
  },
  {
    "libraryControlledTerminologyId": 199,
    "libraryControlledTerminologyGuid": "E07065F8-2B41-4F80-9F9A-C8C3A15E2857",
    "libraryControlledTerminologyCategoryId": 10,
    "parentId": null,
    "isFolder": false,
    "libraryControlledTerminologyNameShort": "Imagine",
    "libraryControlledTerminologyNameLong": "Imagine",
    "libraryControlledTerminologyDescription": "Imagine",
    "isCustom": false,
    "isHidden": false,
    "displayOrder": 7
  }
  ]